### ISSUE TITLE
1조 화이팅~~~ 

### ISSUE THREAD

**Issue by move02** [nicesick/GongJo#30]
https://github.com/nicesick/GongJo/blob/327f8e549412ad290ca8814b68f1d1f52708d9f1/ConnectedCarControlSystem/src/com/controller/RegisterController.java#L89

과제하다가 심심해서 구경!
차량 등록할 때 Front단은 못봤지만 Back단에서도 입력한 정보에 대해 Validation이 필요할 것 같아요 ^.^

**Comment by nicesick** [comment]
어맛...
감사합니다 ^.^

보고싶습니당 :)

**Comment by JYn0** [comment]
시간될때 놀러와

**Comment by move02** [comment]
아무때나 가능하니 불러주세욘

**Comment by JYn0** [comment]
내일 오래

**Comment by jkim0715** [comment]
동영아 어서오고
